#!/usr/bin/env python3
"""Backfill image provenance, refresh paths, and recompute image metadata in existing sidecars."""

import hashlib
import json
import mimetypes
import os
import struct
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

PROMPT_UNRETAINED_NOTE = (
    "Generated by ChatGPT using the OpenAI image gen tool at generation time; "
    "the exact prompt was not preserved."
)

SIDECARS = [
    {
        "sidecar": "published/fairytales/goldilocks/page__right_amount_of_guidance__v1-sidecar.json",
        "image": "published/fairytales/goldilocks/page__right_amount_of_guidance__v1.png",
        "generated_at": None,
    },
    {
        "sidecar": "published/fairytales/goldilocks/scene__just_right__v1-sidecar.json",
        "image": "published/fairytales/goldilocks/scene__just_right__v1.png",
        "generated_at": "2026-08-14T06:58:19Z",
    },
    {
        "sidecar": "published/fairytales/goldilocks/scene__not_enough__v1-sidecar.json",
        "image": "published/fairytales/goldilocks/scene__not_enough__v1.png",
        "generated_at": "2026-08-14T06:58:19Z",
    },
    {
        "sidecar": "published/fairytales/goldilocks/scene__too_much__v1-sidecar.json",
        "image": "published/fairytales/goldilocks/scene__too_much__v1.png",
        "generated_at": "2026-08-14T06:58:19Z",
    },
    {
        "sidecar": "published/fairytales/sorcerers-apprentice/detail__delegation_instruction_circle__v1-sidecar.json",
        "image": "published/fairytales/sorcerers-apprentice/detail__delegation_instruction_circle__v1.png",
        "generated_at": None,
    },
    {
        "sidecar": "published/fairytales/sorcerers-apprentice/detail__delegation_instruction_closeup__v1-sidecar.json",
        "image": "published/fairytales/sorcerers-apprentice/detail__delegation_instruction_closeup__v1.png",
        "generated_at": None,
    },
    {
        "sidecar": "published/fairytales/sorcerers-apprentice/page__delegation_without_boundaries__v1-sidecar.json",
        "image": "published/fairytales/sorcerers-apprentice/page__delegation_without_boundaries__v1.png",
        "generated_at": None,
    },
    {
        "sidecar": "published/fairytales/sorcerers-apprentice/prop__delegation_policy__v1-sidecar.json",
        "image": "published/fairytales/sorcerers-apprentice/prop__delegation_policy__v1.png",
        "generated_at": None,
    },
    {
        "sidecar": "published/fairytales/sorcerers-apprentice/scene__five_worker_handoff__v1-sidecar.json",
        "image": "published/fairytales/sorcerers-apprentice/scene__five_worker_handoff__v1.png",
        "generated_at": None,
    },
    {
        "sidecar": "published/fairytales/sorcerers-apprentice/scene__runaway_recursive_delegation__v1-sidecar.json",
        "image": "published/fairytales/sorcerers-apprentice/scene__runaway_recursive_delegation__v1.png",
        "generated_at": None,
    },
    {
        "sidecar": "build/characters/heist-crew/reference_sheets/index_hero__v1-sidecar.json",
        "image": "build/characters/heist-crew/reference_sheets/index_hero__v1.png",
        "generated_at": "2026-06-13T07:40:44Z",
    },
    {
        "sidecar": "build/characters/heist-crew/reference_sheets/index_style_sheet__v1-sidecar.json",
        "image": "build/characters/heist-crew/reference_sheets/index_style_sheet__v1.png",
        "generated_at": "2026-06-13T07:40:44Z",
    },
    {
        "sidecar": "build/characters/heist-crew/reference_sheets/index_anti_patterns__v1-sidecar.json",
        "image": "build/characters/heist-crew/reference_sheets/index_anti_patterns__v1.png",
        "generated_at": "2026-06-13T07:40:44Z",
    },
]


def _png_info(path: Path) -> dict:
    with open(path, "rb") as f:
        sig = f.read(8)
        if sig != b"\x89PNG\r\n\x1a\n":
            raise ValueError(f"{path} is not a PNG")
        length = struct.unpack(">I", f.read(4))[0]
        chunk_type = f.read(4)
        if chunk_type != b"IHDR":
            raise ValueError(f"{path} has no IHDR chunk")
        if length != 13:
            raise ValueError(f"{path} has unexpected IHDR length")
        width, height = struct.unpack(">II", f.read(8))
        bit_depth, color_type = struct.unpack(">BB", f.read(2))
        return {
            "width": width,
            "height": height,
            "mode": _png_mode(color_type),
            "bit_depth": bit_depth,
            "color_type": color_type,
        }


def _png_mode(color_type: int) -> str:
    if color_type == 0:
        return "L"
    if color_type == 2:
        return "RGB"
    if color_type == 3:
        return "P"
    if color_type == 4:
        return "LA"
    if color_type == 6:
        return "RGBA"
    return f"unknown:{color_type}"


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()


def _expected_mime(filename: str) -> str:
    return mimetypes.guess_type(filename, strict=False)[0] or "image/png"


def provenance(generated_at: str | None) -> dict:
    p = {
        "generator": "ChatGPT / OpenAI image generation",
        "model": "gpt-image-2",
        "generated_at": generated_at,
        "prompt_language": "en",
        "prompt": None,
        "prompt_retained": False,
        "prompt_unretained_note": PROMPT_UNRETAINED_NOTE,
    }
    return p


def image_metadata(image_path: Path) -> dict:
    info = _png_info(image_path)
    return {
        "sha256": _sha256(image_path),
        "byte_size": os.path.getsize(image_path),
        "mime_type": _expected_mime(image_path.name),
        "dimensions": {"width": info["width"], "height": info["height"]},
        "mode": info["mode"],
    }


def main() -> int:
    for entry in SIDECARS:
        sidecar_path = ROOT / entry["sidecar"]
        image_path = ROOT / entry["image"]
        with open(sidecar_path, "r", encoding="utf-8") as f:
            data = json.load(f)

        data.setdefault("image", {})
        data["image"]["provenance"] = provenance(entry["generated_at"])
        data["image"]["repo_image_path"] = entry["image"]
        data["image"]["repo_sidecar_path"] = entry["sidecar"]
        data["image"]["image_filename"] = image_path.name
        data["image"]["relative_image_path"] = image_path.name
        data["image"]["relative_sidecar_path"] = sidecar_path.name
        data["image"].update(image_metadata(image_path))

        with open(sidecar_path, "w", encoding="utf-8", newline="\n") as f:
            json.dump(data, f, indent=2, ensure_ascii=False)
            f.write("\n")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
